# Site settings
title: Jon Charter -- Graphic Design and Photography
email: JMCharter@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://joncharter.co.uk" # the base hostname & protocol for your site
twitter_username: joncharter
github_username:  JMCharter

# Build settings
markdown: kramdown

#Gems
gems: [bourbon, neat]